# 本文件定义和编写与环境相关的容器
version: "2.0"
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: gyu-mysql # 启动的实例名称
    ports:
      - "33061:3306" # 端口映射
    environment:
      MYSQL_ROOT_PASSWORD: 123 # root 密码
      MYSQL_DATABASE: blog_service # 数据库名称
      MYSQL_PASSWORD: 123 # 数据库密码
      MYSQL_USER: gyu # 数据库用户名
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 启动脚本
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以防丢失
    restart: always # 奔溃后自动重启
    networks:
      - gyu_blog_net # 指定网络
networks:
  gyu_blog_net: